### PR TITLE
Clarify `f16` maths - closes #204

### LINKED ISSUE #204: Exercise 60 incorrectly states that var foo: f16 = 13.5 * 5; does not compile
Exercise 60 states:
```
// A float literal has a decimal point. When performing math
// operations with numeric literals, ensure the types match. Zig
// does not perform unsafe type coercions behind your back:
//
//     var foo: f16 = 13.5 * 5;   // ERROR!
//     var foo: f16 = 13.5 * 5.0; // No problem, both are floats
```

Yet the following code compiles and runs as expected by the exercise:
```
var shuttle_weight: f32 = 907.18 * 2200;
```
Output:
```
Compiling 060_floats.zig...
Checking 060_floats.zig...
PASSED:
Shuttle liftoff weight: 1995796kg 
```

Tested with Zig 0.11.0-dev.1987+a2c6ecd6d (because I like being able to use `zig build` :) )

### PR DESCRIPTION
**Pull request by Arya-Elfren**

### CODE REVIEW

File: exercises/060_floats.zig [hunk 1]
```diff
@@ -1,7 +1,8 @@
 //
 // Zig has support for IEEE-754 floating-point numbers in these
 // specific sizes: f16, f32, f64, f80, and f128. Floating point
-// literals may be written in scientific notation:
+// literals may be written in the same ways as integers but also
+// in scientific notation:
```
Comment (ratfactor) [inline exercises/060_floats.zig:5]: Good, thanks!

File: exercises/060_floats.zig [hunk 2]
```diff
@@ -26,7 +27,10 @@
 // operations with numeric literals, ensure the types match. Zig
 // does not perform unsafe type coercions behind your back:
 //
-//     var foo: f16 = 13.5 * 5;   // ERROR!
+//     fn foo(bar: u16) f16 { return 13.5 * bar; } // ERROR!
+//     var foo: f16 = 13.5 * @as(u8, 5); // ERROR!
+//     var foo: f16 = 13.5 * 5; // This is a safe compile-time
+//                              // conversion, so no problem!
```
Comment (ratfactor) [inline exercises/060_floats.zig:33]: Yeah, those examples certainly work...  But I played around a bit and realized that we can actually get the original behavior with two variables (`float_var = int_var` produces the original error).

I think the multiplication is just getting in the way of the example now.

But you're right, it _would_ be nice to also demonstrate the compile-time conversion. So how about this to demonstrate the difference:

```
    var u_foo: u16 = 5;
    var float_foo: f16 = u_foo; // ERROR! (Runtime type conversion.)
    var float_foo: f16 = 5; // Fine! (Safe compile-time numeric evaluation.)
```

What do you think?

**Comment by chrboesch** [comment]
Please note that any changes in an exercise also requires a change of the patch file. Otherwise the (new) tests will fail.

File: exercises/060_floats.zig [hunk 3]
```diff
@@ -23,15 +23,12 @@
...
 // operations with numeric literals, ensure the types match. Zig
 // does not perform unsafe type coercions behind your back:
 //
-//     fn foo(bar: u16) f16 { return 13.5 * bar; } // ERROR!
-//     var foo: f16 = 13.5 * @as(u8, 5); // ERROR!
-//     var foo: f16 = 13.5 * 5; // This is a safe compile-time
-//                              // conversion, so no problem!
-//     var foo: f16 = 13.5 * 5.0; // No problem, both are floats
+//    var foo: f16 = 5; // NO ERROR
+//    var foo: f16 = @as(u16, 5); // ERROR
```
Comment (ratfactor) [inline exercises/060_floats.zig:31]: I hate to be a stickler, but we don't introduce builtins like `@as()` until a couple exercises later. I don't want anyone to think that this `@...` stuff has anything to do with the ERROR we are demonstrating. I think we should use only concepts that have already been introduced.

File: exercises/060_floats.zig [hunk 4]
```diff
@@ -23,15 +23,12 @@
 //     const pi: f16 = 3.1415926535;   // rounds to 3.140625
 //     const av: f16 = 6.02214076e+23; // Avogadro's inf(inity)!
 //
-// A float literal has a decimal point. When performing math
+// A float literal doesn't need a decimal point. When performing math
 // operations with numeric literals, ensure the types match. Zig
 // does not perform unsafe type coercions behind your back:
```
Comment (ratfactor) [inline exercises/060_floats.zig:28]: I like your change.  Now I'm realizing the part about "math operations" doesn't really follow the first sentence or even reflect how Zig works anymore. Maybe split this into two paragraphs?

```
// A float literal can have a decimal point, but it doesn't require one.
//
// // When dealing with numeric literals, ensure the types match. Zig does not
// perform unsafe type coercions behind your back:
```

File: exercises/060_floats.zig (hunk 2 above)
Comment (ratfactor) [reply exercises/060_floats.zig]: Yes, I think we agree!

I responded to the commit before I saw your comment. I like the change.

But I would like to move away from using `@as()` in the example (see code review comment).

File: exercises/060_floats.zig (hunk 4 above)
Comment (Arya-Elfren) [reply exercises/060_floats.zig]: Mentioning that float literals don't need a decimal point is just necessary because other languages need one. I think we can leave it implicit with an example.

**Comment by ratfactor** [comment]
@Arya-Elfren Looks great. Thank you for this improvement!
